# Generated by Django 5.0.4 on 2025-05-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='postagens.post'),
            preserve_default=False,
        ),
    ]
